import type { ThemeTokens } from '@/features/themes/tokens';

/**
 * Originalne teme za demo šablone (zahtev 11 i 35).
 *
 * Svaka paleta je birana tako da prolazi proveru kontrasta iz
 * `src/features/themes/contrast.ts` - test `themes.test.ts` to i proverava, pa
 * nečitljiva tema ne može da uđe u seed.
 */
export type SeedTheme = { key: string; name: string; tokens: ThemeTokens };

export const seedThemes: SeedTheme[] = [
  {
    key: 'editorial-ivory',
    name: 'Editorial ivory',
    tokens: {
      palette: {
        background: '#f7f4ef',
        surface: '#ffffff',
        text: '#241f1c',
        textMuted: '#5c534b',
        accent: '#3f3a34',
        accentContrast: '#ffffff',
        border: '#ddd5c9',
      },
      fontPair: 'serif-editorial',
      typeScale: 'medium',
      density: 'airy',
      radius: 'sharp',
      shadow: 'none',
      buttonStyle: 'outline',
      cardStyle: 'flat',
      dividerStyle: 'line',
      backgroundStyle: 'plain',
      motion: 'subtle',
      iconStyle: 'line',
      ornaments: [],
    },
  },
  {
    key: 'botanical-blush',
    name: 'Botanički blush',
    tokens: {
      palette: {
        background: '#fbf6f4',
        surface: '#ffffff',
        text: '#3b2a2c',
        textMuted: '#6b5457',
        accent: '#8a4a55',
        accentContrast: '#ffffff',
        border: '#ecdcd8',
      },
      fontPair: 'serif-romantic',
      typeScale: 'medium',
      density: 'comfortable',
      radius: 'soft',
      shadow: 'soft',
      buttonStyle: 'solid',
      cardStyle: 'paper',
      dividerStyle: 'botanical',
      backgroundStyle: 'texture-paper',
      motion: 'balanced',
      iconStyle: 'line',
      ornaments: ['leaf-branch', 'small-bloom'],
    },
  },
  {
    key: 'midnight-velvet',
    name: 'Ponoćni baršun',
    tokens: {
      palette: {
        background: '#151217',
        surface: '#1f1a22',
        text: '#f4f0f2',
        textMuted: '#b3a7ad',
        accent: '#c9a34e',
        accentContrast: '#1a1418',
        border: '#3a3140',
      },
      fontPair: 'mixed-classic',
      typeScale: 'large',
      density: 'comfortable',
      radius: 'soft',
      shadow: 'lifted',
      buttonStyle: 'solid',
      cardStyle: 'elevated',
      dividerStyle: 'ornament',
      backgroundStyle: 'gradient',
      motion: 'balanced',
      iconStyle: 'duotone',
      ornaments: ['thin-frame'],
    },
  },
  {
    key: 'sacral-linen',
    name: 'Sakralno platno',
    tokens: {
      palette: {
        background: '#f8f7f3',
        surface: '#ffffff',
        text: '#2a2b28',
        textMuted: '#5a5c56',
        // Tamnija maslina: raniji ton (#6f7d5e) davao je 4.4:1 sa belim tekstom,
        // tik ispod WCAG AA praga - test kontrasta ga je odbio.
        accent: '#5f6c50',
        accentContrast: '#ffffff',
        border: '#e0e0d6',
      },
      fontPair: 'serif-editorial',
      typeScale: 'medium',
      density: 'airy',
      radius: 'soft',
      shadow: 'none',
      buttonStyle: 'soft',
      cardStyle: 'bordered',
      dividerStyle: 'ornament',
      backgroundStyle: 'texture-linen',
      motion: 'subtle',
      iconStyle: 'line',
      ornaments: ['olive-branch'],
    },
  },
  {
    key: 'cloud-watercolor',
    name: 'Akvarel oblaci',
    tokens: {
      palette: {
        background: '#f4f8fb',
        surface: '#ffffff',
        text: '#26333d',
        textMuted: '#54636e',
        accent: '#3f6f8f',
        accentContrast: '#ffffff',
        border: '#d9e4ec',
      },
      fontPair: 'sans-modern',
      typeScale: 'medium',
      density: 'comfortable',
      radius: 'rounded',
      shadow: 'soft',
      buttonStyle: 'soft',
      cardStyle: 'flat',
      dividerStyle: 'dots',
      backgroundStyle: 'gradient',
      motion: 'balanced',
      iconStyle: 'line',
      ornaments: ['cloud'],
    },
  },
  {
    key: 'teddy-honey',
    name: 'Meda i med',
    tokens: {
      palette: {
        background: '#fdf7ef',
        surface: '#ffffff',
        text: '#3a2c1e',
        textMuted: '#6a5540',
        accent: '#a5652a',
        accentContrast: '#ffffff',
        border: '#efe0cd',
      },
      fontPair: 'display-playful',
      typeScale: 'large',
      density: 'comfortable',
      radius: 'rounded',
      shadow: 'soft',
      buttonStyle: 'solid',
      cardStyle: 'paper',
      dividerStyle: 'dots',
      backgroundStyle: 'texture-paper',
      motion: 'expressive',
      iconStyle: 'solid',
      ornaments: ['paw', 'star-small'],
    },
  },
  {
    key: 'balloon-pastel',
    name: 'Pastelni baloni',
    tokens: {
      palette: {
        background: '#fdf6f9',
        surface: '#ffffff',
        text: '#332430',
        textMuted: '#63505d',
        accent: '#9c4577',
        accentContrast: '#ffffff',
        border: '#f0dee8',
      },
      fontPair: 'sans-geometric',
      typeScale: 'large',
      density: 'comfortable',
      radius: 'pill',
      shadow: 'soft',
      buttonStyle: 'solid',
      cardStyle: 'elevated',
      dividerStyle: 'dots',
      backgroundStyle: 'plain',
      motion: 'expressive',
      iconStyle: 'solid',
      ornaments: ['balloon', 'confetti'],
    },
  },
  {
    key: 'neon-night',
    name: 'Neonska noć',
    tokens: {
      palette: {
        background: '#0f1117',
        surface: '#181b24',
        text: '#f2f4f8',
        textMuted: '#a8aec0',
        accent: '#4ad8c0',
        accentContrast: '#0d1015',
        border: '#2c313f',
      },
      fontPair: 'sans-geometric',
      typeScale: 'large',
      density: 'compact',
      radius: 'sharp',
      shadow: 'lifted',
      buttonStyle: 'solid',
      cardStyle: 'elevated',
      dividerStyle: 'line',
      backgroundStyle: 'gradient',
      motion: 'expressive',
      iconStyle: 'solid',
      ornaments: ['glow-line'],
    },
  },
];
